name: Update Euroleague Data

# At 09:30UTC daily (20:30 Melbourne daylight saving time time).
on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "30 9 * * *"

jobs:
  update-euroleage-data:
    runs-on: macos-13
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.NBLR_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Package Installation
        run: Rscript -e 'install.packages(c("remotes", "dplyr", "tidyr", "httr", "rlang", "here", "piggyback"))'
      - name: euroleagueRscrape Installation
        run: Rscript -e 'remotes::install_github("JaseZiv/euroleagueRscrape")'
      - name: Update season round metadata
        run: Rscript -e 'source(file.path("get-data", "updating", "update_season_rounds.R"), echo = TRUE)'
      - name: Update match results
        run: Rscript -e 'source(file.path("get-data", "updating", "update_match_results.R"), echo = TRUE)'
      - name: Update box scores
        run: Rscript -e 'source(file.path("get-data", "updating", "update_box_scores.R"), echo = TRUE)'
      - name: Update pbp
        run: Rscript -e 'source(file.path("get-data", "updating", "update_pbp.R"), echo = TRUE)'
      - name: Update shots
        run: Rscript -e 'source(file.path("get-data", "updating", "update_shots.R"), echo = TRUE)'
      - name: Update csv files
        run: Rscript -e 'source(file.path("get-data", "updating", "save_csvs.R"), echo = TRUE)'
      - name: Update player bios
        run: Rscript -e 'source(file.path("get-data", "updating", "update_player_bios.R"), echo = TRUE)'
